export const imageCollections = {
    centrifugal: [
        { src: "/assets/centrifugal/01.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/02.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/03.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/04.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/05.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/06.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/07.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/08.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/09.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/10.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/11.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/centrifugal/12.png", caption: "Beautiful Landscape 1" },

    ],
    gearbox_bottom: [
        { src: "/assets/gear_box_bottom/1.jpg", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_bottom/2.jpg", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_bottom/3.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_bottom/4.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_bottom/5.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_bottom/6.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_bottom/7.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_bottom/8.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_bottom/9.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_bottom/10.png", caption: "Beautiful Landscape 1" },
    ],
    gearbox_top: [
        { src: "/assets/gear_box_top/1.jpg", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_top/2.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_top/3.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_top/4.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_top/5.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_top/6.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_top/7.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_top/8.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_top/9.png", caption: "Beautiful Landscape 1" },
    ],
    gear_box_cover: [
        { src: "/assets/gear_box_cover/1.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_cover/2.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_cover/3.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_cover/4.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_cover/5.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_cover/6.png", caption: "Beautiful Landscape 1" },
    ],
    gear_box_casing_1: [
        { src: "/assets/gear_box_casing_1/1.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_1/2.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_1/3.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_1/4.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_1/5.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_1/6.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_1/7.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_1/8.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_1/10.png", caption: "Beautiful Landscape 1" },
    ],
    gear_box_casing_2: [
        { src: "/assets/gear_box_casing_2/1.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_2/2.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_2/3.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_2/4.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_2/5.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_2/6.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_2/7.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/gear_box_casing_2/8.png", caption: "Beautiful Landscape 1" },
    ],
    throttle_body: [
        { src: "/assets/throttle_body/1.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/throttle_body/2.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/throttle_body/3.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/throttle_body/4.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/throttle_body/5.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/throttle_body/6.png", caption: "Beautiful Landscape 1" },
    ],
    oil_sump_core_box: [
        { src: "/assets/oil_sump_core_box/1.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/oil_sump_core_box/2.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/oil_sump_core_box/4.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/oil_sump_core_box/5.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/oil_sump_core_box/6.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/oil_sump_core_box/7.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/oil_sump_core_box/3.png", caption: "Beautiful Landscape 1" },
    ],
    duct_1: [
        { src: "/assets/duct_1/1.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/duct_1/2.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/duct_1/3.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/duct_1/4.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/duct_1/5.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/duct_1/6.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/duct_1/7.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/duct_1/8.png", caption: "Beautiful Landscape 1" },
    ],
    pneumatic_cyclinder: [
        { src: "/assets/pneumatic_cyclinder/1.jpg", caption: "Beautiful Landscape 1" },
        { src: "/assets/pneumatic_cyclinder/2.jpg", caption: "Beautiful Landscape 1" },
        { src: "/assets/pneumatic_cyclinder/3.jpeg", caption: "Beautiful Landscape 1" },
        { src: "/assets/pneumatic_cyclinder/4.png", caption: "Beautiful Landscape 1" },
        { src: "/assets/pneumatic_cyclinder/5.jpg", caption: "Beautiful Landscape 1" },
    ]

}